const ADD_NUMBER = 'ADD_NUMBER';
const SUB_NUMBER = 'SUB_NUMBER';
const CHANGE_BANNER = 'CHANGE_BANNER';
const CHANGE_RECOMMEND = 'CHANGE_RECOMMEND';

export {
    ADD_NUMBER,
    SUB_NUMBER,
    CHANGE_BANNER,
    CHANGE_RECOMMEND
}